# Generated by Django 5.0.6 on 2026-04-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create',
            new_name='created',
        ),
    ]
